version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    group:
      dev-dependencies:
        - dependency-type: "development"
      dependencies:
        - dependency-type: "direct"

    open-pull-requests-limit: 5
    target-branch: "main"
    allow:
      - dependency-type: "development"
        # Removed the update-types field as it is not supported here
      - dependency-type: "direct"
        # Removed the update-types field as it is not supported here
    # ignore:
    #   - dependency-name: "some-package-name"
    #     versions: ["1.2.3"]
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "npm: "

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"
    allow:
      - dependency-name: "ghcr.io/flxbl-io/sfp-rc"
    commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "docker: "
