name: Copy and Rename READMEs

on:
  push:
    branches:
      - main
    paths:
      - "sfdx-project.json"
      - "src/**/README.md"

jobs:
  copy_rename_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Run script to copy README.md files
        run: node scripts/docs/copyReadmes.js
