name: "CD Pipeline - User Triggered"

on:
  workflow_dispatch:
    inputs:
      release-def-path:
        description: "Path to release definition file"
        required: true

jobs:
  sit-release:
    uses: b64hub/sf-actions/.github/workflows/release.yml@main
    if: github.ref == 'refs/heads/main' || contains(github.ref,'refs/heads/release')
    with:
      release-def-path: ${{ github.event.inputs.release-def-path }}
    secrets:
      ENV_SFDX_AUTH_URL: ${{ secrets.SIT_SFDX_AUTH_URL }}
    env:
      SFPOWERSCRIPTS_DATADOG: "true"
      SFPOWERSCRIPTS_DATADOG_HOST: "${{ vars.DATADOG_HOST }}"
      SFPOWERSCRIPTS_DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"

  release:
    strategy:
      matrix:
        env: [dev, prod]
        include:
          - env: dev
            sfdxurl_secret: ${{ secrets.UAT_SFDX_AUTH_URL }}
          - env: prod
            sfdxurl_secret: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
    uses: b64hub/sf-actions/.github/workflows/release.yml@main
    if: contains(github.ref,'refs/heads/release')
    with:
      release-def-path: ${{ github.event.inputs.release-def-path }}
    secrets:
      ENV_SFDX_AUTH_URL: ${{ secrets[matrix.sfdxurl_secret] }}
    env:
      SFPOWERSCRIPTS_DATADOG: "true"
      SFPOWERSCRIPTS_DATADOG_HOST: "${{ vars.DATADOG_HOST }}"
      SFPOWERSCRIPTS_DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"
